### ISSUE TITLE
OIDC authentication repeating and getting session timed out

### ISSUE THREAD

**Issue by subasathees** [arrikto/oidc-authservice#117]
**Is this a bug report or feature request?**
* Bug Report

**Describe the bug**
Hi Team, 
Facing authentication related issue with oidc login after upgrading kubeflow from v1.3.1 to v1.7.0 (kubernetes upgrade from v1.19 to v1.23.5 ). This was working fine with older custom build image(oidc:28c59ef-dirty-ce9bd6). but when we use default image(oidc-authservice:e236439) this is not working. We are running pingid for sso auth.

![image](https://github.com/arrikto/oidc-authservice/assets/74454989/67c48238-9f0a-4e68-aa8f-2e7220956b04)

**How to Reproduce**
1. Deploy AuthService ... 
2. Perform this action ...
3. See error

**Expected behavior**
successful authentication with pingid oidc sso and land on the kubeflow page, also proper logout from page.

**Config Files**
- AuthService configuration.
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authservice-web
  namespace: istio-system
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /authservice/
      rewrite:
        uri: /
      route:
        - destination:
            host: authservice.istio-system.svc.cluster.local
            port:
              number: 8082
```
Patched the service with port 8082: -  authservice in istio-system namespace
```
  ports:
  - name: http-authservice
    port: 8080
    protocol: TCP
    targetPort: http-api
  - name: http-web
    port: 8082
    protocol: TCP
    targetPort: http-web
```

- OIDC Provider configuration.

File: common/oidc-authservice/base/params.env
```
OIDC_PROVIDER=https://auth.example.com
OIDC_AUTH_URL=https://auth.example.com/as/authorization.oauth2
OIDC_SCOPES=openid,profile,email
AUTHSERVICE_URL_PREFIX=/authservice/
REDIRECT_URL=https://kfserver.example.com/login/oidc
USERID_HEADER=kubeflow-userid
USERID_PREFIX=
USERID_CLAIM=email
AFTER_LOGOUT_URL=https://auth.example.com/idp/startSLO.ping
PORT="8080"
LOG_LEVEL="DEBUG"
SKIP_AUTH_URLS=/dex
STORE_PATH=/var/lib/authservice/data.db
```

If relevant, upload your configuration files here using GitHub, there is no need
to upload them to any 3rd party services

**Logs**
```
$ kubectl logs -n istio-system authservice-0 
time="2023-07-17T11:23:13Z" level=info msg="Config: &{ProviderURL:https://auth.example.com ClientID:kubeflow-oidc-authservice_OIDC ClientSecret:xxxxxx-xxx-xx OIDCAuthURL:https://auth.example.com/as/authorization.oauth2 RedirectURL:https://kubeflow.example.com/login/oidc OIDCScopes:[openid openid profile email] StrictSessionValidation:false OIDCStateStorePath:/var/lib/authservice/data.db AuthserviceURLPrefix:/authservice/ SkipAuthURLs:[/authservice/ /dex] AuthHeader:Authorization Audiences:[istio-ingressgateway.istio-system.svc.cluster.local] HomepageURL:/authservice/site/homepage AfterLoginURL: AfterLogoutURL:https://auth.example.com/idp/startSLO.ping UserIDHeader:kubeflow-userid GroupsHeader:kubeflow-groups UserIDPrefix: UserIDTransformer:{rules:[]} UserIDClaim:email UserIDTokenHeader: GroupsClaim:groups IDTokenHeader:Authorization Hostname: Port:8080 WebServerPort:8082 ReadinessProbePort:8081 CABundlePath: SessionStorePath:/var/lib/authservice/data.db SessionMaxAge:86400 SessionSameSite:Lax ClientName:AuthService ThemesURL:themes Theme:kubeflow TemplatePath:[web/templates/default] UserTemplateContext:map[] GroupsAllowlist:[*]}"
time="2023-07-17T11:23:13Z" level=info msg="Starting readiness probe at 8081"
time="2023-07-17T11:23:13Z" level=info msg="Starting server at :8080"
time="2023-07-17T11:23:13Z" level=info msg="Starting web server at :8082"

time="2023-07-17T11:23:39Z" level=info msg="Authenticating request..." ip=10.233.12.32 request=/
time="2023-07-17T11:23:39Z" level=info msg="Loading session from cookie authservice_session" ip=10.233.12.32 request=/
time="2023-07-17T11:23:39Z" level=info msg="Failed to authenticate using authenticators. Initiating OIDC Authorization Code flow..." ip=10.233.12.32 request=/
time="2023-07-17T11:24:19Z" level=info msg="Authenticating request..." ip=10.233.12.32 request="/login/oidc?code=Avb2KRXFUUupqrXTy_Y_fRckh774fL1Xj_IAAABl&state=MTY4OTU5MzAxOXxOd3dBTkVKRFNsaExWalJVV2xNMlVGZFJRbFZXV0RSRU16WlhNMFZLVWxWQ1RqSklUMUpJUkU5S1RFTllXRE5NV2pZeVZGcEdSa0U9fP4gHQZFDzLyul3kv0eQwYA7hNi2ltQIbiU7yGCt3oFX"
time="2023-07-17T11:24:19Z" level=info msg="Loading session from cookie authservice_session" ip=10.233.12.32 request="/login/oidc?code=Avb2KRXFUUupqrXTy_Y_fRckh774fL1Xj_IAAABl&state=MTY4OTU5MzAxOXxOd3dBTkVKRFNsaExWalJVV2xNMlVGZFJRbFZXV0RSRU16WlhNMFZLVWxWQ1RqSklUMUpJUkU5S1RFTllXRE5NV2pZeVZGcEdSa0U9fP4gHQZFDzLyul3kv0eQwYA7hNi2ltQIbiU7yGCt3oFX"
time="2023-07-17T11:24:19Z" level=info msg="Failed to authenticate using authenticators. Initiating OIDC Authorization Code flow..." ip=10.233.12.32 request="/login/oidc?code=Avb2KRXFUUupqrXTy_Y_fRckh774fL1Xj_IAAABl&state=MTY4OTU5MzAxOXxOd3dBTkVKRFNsaExWalJVV2xNMlVGZFJRbFZXV0RSRU16WlhNMFZLVWxWQ1RqSklUMUpJUkU5S1RFTllXRE5NV2pZeVZGcEdSa0U9fP4gHQZFDzLyul3kv0eQwYA7hNi2ltQIbiU7yGCt3oFX"
time="2023-07-17T11:24:19Z" level=info msg="Authenticating request..." ip=10.233.12.32 request="/login/oidc?code=swnn0GLVicUYK5tjGqWcLXxWPIgcHU8Jg28AAABl&state=MTY4OTU5MzA1OXxOd3dBTkZKWlQxazFURXhGU1ZGS05rVlpRMUJYVGs1R01sUlVRa0UwUlRRelJrZFRObEZIUzBwVlJrbGFVMFJPVlRKYVdrZEdNMEU9fHMq4ncpS8RiV7Do75cDIbaNQx8LDfaR8ZBZr2n0QMWY"

```

**Environment:**
- AuthService version: oidc-authservice:e236439
- Platform: On-premise
- Kubernetes version: v1.23.5
- Kubeflow version: v1.7.0

**Additional context**
We are running pingid for sso, Old custom build image is working fine, but unable to track what was the changes made on the image, based on analysis found port 8082 is removed on the custom image including few changes, however new image after upgrade to kf1.7.0 login page is keep on retrying and getting session expired.
need more information about the oidc setup which is not clear on the kf document.

**Comment by j23zsxc** [comment]
Got same issue on our environment, @subasathees, was this issue fixed on your environment?

**Comment by subasathees** [comment]
@j23zsxc Yes, It's fixed.

Here is the fix for the same, This happens due to URL_PREFIX and old image.
AUTHSERVICE_URL_PREFIX=/authservice/

**All below followed to fix the issue:**
1. Updated default image to New image i.e **gcr.io/arrikto/oidc-authservice:0c4ea9a**
2. Added below empty values in , as in my env we are not having groups scope defined in AD SSO level.

File: common/oidc-authservice/base/params.env  (Append below )
```
GROUPS_HEADER=
GROUPS_CLAIM=
```

3. Added logout proxy redirection, so that logout button works.

File: authservice-logout.yaml
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authservice-logout
  namespace: istio-system
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /logout
      rewrite:
        uri: /authservice/logout
      route:
        - destination:
            host: authservice.istio-system.svc.cluster.local
            port:
              number: 8080
``` 
```
kubectl apply -f authservice-logout.yaml
```
It's Working Now.
