### ISSUE TITLE
server: add options for whitelisted hostnames

### ISSUE THREAD

**Issue by yanniszark** [arrikto/oidc-authservice#13]
Add the option to whitelist hostnames in the authservice.
The hostname is found from the `Host` header.

**Comment by bharath-krishna** [comment]
Hi, is there any updates on this issue?

**Comment by bharath-krishna** [comment]
One way I found is to assign host url to kubeflow-gateway, so that kubeflow can be access only with that URL/host
and create another gateway for all unauthenticated requests.

But this requires "/" to be added to `SKIP_AUTH_URI ` and that breaks kubeflow.

So we need another way to whitelist hostnames.

**Comment by edwardzjl** [comment]
@bharath-krishna For the time I'm writing this comment it can be achieved by custom the external authz provider, here's how:

1. Remove the `EnvoyFilter` authn-filter ([this file](https://github.com/kubeflow/manifests/blob/v1.6.1/common/oidc-authservice/base/envoy-filter.yaml))
2. Add authservice as a `extensionProviders` in istio's mesh config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    ...
    extensionProviders:
    - name: authservice
      envoyExtAuthzHttp:
        service: authservice.istio-system.svc.cluster.local
        port: 8080
        includeRequestHeadersInCheck:
        - cookie
        - authorization
        - x-auth-token
        headersToUpstreamOnAllow:
        - kubeflow-userid
        headersToDownstreamOnDeny:
        - set-cookie
        - content-type
    ...
```
3. Authorize all requests to kubeflow by `AuthorizationPolicy`:
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: authservice
  rules:
    - to:
        - operation:
            hosts:
              - ${YOUR_KUBEFLOW_HOSTNAME}
            paths:
              - /*
  selector:
    matchLabels:
      app: istio-ingressgateway
```

FYI I'm using istio 1.14
